name: mnemoshema
description: Интерактивная электрическая схема

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/avr/akb1off.png
      - assets/images/avr/akb1on.png
      - assets/images/avr/akb1zz.png
      - assets/images/avr/avr1off.png
      - assets/images/avr/avr1on.png
      - assets/images/avr/avr1zz.png
      - assets/images/avr/avrukz1off.png
      - assets/images/avr/avrukz1on.png
      - assets/images/avr/avrukz1zz.png
      - assets/images/avr/dg1off.png
      - assets/images/avr/dg1on.png
      - assets/images/avr/dg1zz.png

      - assets/images/vv/vv1off.png
      - assets/images/vv/vv1on.png
      - assets/images/vv/vv1zz.png
      - assets/images/vv/ps1off.png
      - assets/images/vv/ps1on.png
      - assets/images/vv/ps1zz.png

      - assets/images/lr/lr1off.png
      - assets/images/lr/lr1on.png
      - assets/images/lr/lr1zz.png
      - assets/images/lr/lr2off.png
      - assets/images/lr/lr2on.png
      - assets/images/lr/lr2zz.png
      - assets/images/lr/lr3off.png
      - assets/images/lr/lr3on.png
      - assets/images/lr/lr3zz.png
      - assets/images/lr/lr4off.png
      - assets/images/lr/lr4on.png
      - assets/images/lr/lr4zz.png

      - assets/images/tp/mtp1off.png
      - assets/images/tp/mtp1on.png
      - assets/images/tp/mtp1zz.png
      - assets/images/tp/mtp2off.png
      - assets/images/tp/mtp2on.png
      - assets/images/tp/mtp2zz.png
      - assets/images/tp/ukz1off.png
      - assets/images/tp/ukz1on.png
      - assets/images/tp/ukz1zz.png
      - assets/images/tp/zru1off.png
      - assets/images/tp/zru1on.png
      - assets/images/tp/zru1zz.png

      - assets/images/np/namevl1off.png
      - assets/images/np/namevl1on.png
      - assets/images/np/namevl1zz.png

      - assets/images/kl/kl1off.png
      - assets/images/kl/kl1on.png
      - assets/images/kl/kl1zz.png

      - assets/images/lch/ku1off.png
      - assets/images/lch/ku1on.png
      - assets/images/lch/ku1zz.png
      - assets/images/lch/lch1off.png
      - assets/images/lch/lch1on.png
      - assets/images/lch/lch1zz.png
      - assets/images/lch/lch2off.png
      - assets/images/lch/lch2on.png
      - assets/images/lch/lch2zz.png

      - assets/images/vl/vl1on.png
      - assets/images/vl/vl1off.png
      - assets/images/vl/vl1zz.png
      - assets/images/vl/vl2on.png
      - assets/images/vl/vl2off.png
      - assets/images/vl/vl2zz.png
      - assets/images/vl/vl3on.png
      - assets/images/vl/vl3off.png
      - assets/images/vl/vl3zz.png
      - assets/images/vl/vl4on.png
      - assets/images/vl/vl4off.png
      - assets/images/vl/vl4zz.png
      - assets/images/vl/vl5on.png
      - assets/images/vl/vl5off.png
      - assets/images/vl/vl5zz.png
      - assets/images/vl/vl6on.png
      - assets/images/vl/vl6off.png
      - assets/images/vl/vl6zz.png
      - assets/images/vl/op1on.png
      - assets/images/vl/op1off.png
      - assets/images/vl/op1zz.png
           
      - assets/images/np/nmtp1on.png
      - assets/images/np/nmtp1off.png
      - assets/images/np/nmtp1zz.png
      - assets/images/np/nmtp2on.png
      - assets/images/np/nmtp2off.png
      - assets/images/np/nmtp2zz.png
      - assets/images/np/nmtp3on.png
      - assets/images/np/nmtp3off.png
      - assets/images/np/nmtp3zz.png
      - assets/images/np/nmtp4on.png
      - assets/images/np/nmtp4off.png
      - assets/images/np/nmtp4zz.png
      - assets/images/np/nkptm1on.png
      - assets/images/np/nkptm1off.png
      - assets/images/np/nkptm1zz.png
      - assets/images/np/nkptm2on.png
      - assets/images/np/nkptm2off.png
      - assets/images/np/nkptm2zz.png
      - assets/images/np/nkptm3on.png
      - assets/images/np/nkptm3off.png
      - assets/images/np/nkptm3zz.png
      - assets/images/np/nukz1on.png
      - assets/images/np/nukz1off.png
      - assets/images/np/nukz1zz.png
      - assets/images/np/nukz2on.png
      - assets/images/np/nukz2off.png
      - assets/images/np/nukz2zz.png
      - assets/images/np/nukz3on.png
      - assets/images/np/nukz3off.png
      - assets/images/np/nukz3zz.png
      - assets/images/np/nukz4on.png
      - assets/images/np/nukz4off.png
      - assets/images/np/nukz4zz.png
      - assets/images/np/nukz5on.png
      - assets/images/np/nukz5off.png
      - assets/images/np/nukz5zz.png
      - assets/images/np/nukz6on.png
      - assets/images/np/nukz6off.png
      - assets/images/np/nukz6zz.png

      - assets/images/logoWelcomeScreen.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
